### ISSUE TITLE
Using schema name that doesn't exist in OAI spec when calling query

### ISSUE THREAD

**Issue by dhmlau** [strongloop/oasgraph#127]
**Describe the bug**

After creating a ToDo application using LoopBack, here is the OpenAPI spec: 
[openapi.txt](https://github.com/strongloop/oasgraph/files/2954909/openapi.txt)

In the GraphQL explorer, the correct query is
```
query {
  todos2 {
    title
    desc
  }
}
```

instead of 
```
query {
  todos {
    title
    desc
  }
}
```
I'm wondering where is the `todos2` is coming from?  It doesn't seem to be matching the schema name or the endpoints.

**Comment by dhmlau** [comment]
IIRC, at some point, I was using `todos` because we verified our instructions in the Quick Lab here: https://developer.ibm.com/tutorials/create-rest-apis-minutes-with-loopback-4/.

**Comment by ErikWittern** [comment]
@dhmlau The behavior is expected. OASGraph attempts to base field names on the return types of operations. Because, in your OAS, multiple operations return the `Todo` type, OASGraph appends numbers to differentiate the fields.

If you want more control, consider using the `operationIdFieldNames` option (see https://github.com/strongloop/oasgraph/tree/master/packages/oasgraph-cli#usage). If set to true, the `operationId` defined in an OAS operation is used to name that field. This gives developers more fine-grained control over how the GraphQL interface will look like.

**Comment by Alan-Cha** [comment]
@ErikWittern I took a very brief look at this yesterday and if I recall correctly the `todos2` field does not return a `Todos2` object but rather an array of `Todo` objects. The `todos` field name is also not being used. I have some ideas of what may be going on and I’ll try report back later today. However, if you cannot wait, @dhmlau, please consider using the `operationIdFieldNames` option as @ErikWittern has suggested. It should be an easy fix to field name problems.

**Comment by Alan-Cha** [comment]
I took a look at @ErikWittern, you are correct. I wasn't sure if arrays had a different mechanism of creating a field name than objects so I went back to check and it turned out to be same. So just to reiterate, this behavior is expected and it is because multiple operations return a type that share the same type name (which is used for the query field names). 

We could try to make it so that OASGraph tries to give nice looking type names to GET operations (in this case `PATCH /todos` received the `Todos` field name) but this will require a lot of restructuring and naming will always be semi-arbitrary. 

For now, please consider using the `operationIdFieldNames` to manually define field names. Hope this helps!

**Comment by dhmlau** [comment]
@Alan-Cha @ErikWittern , thanks for looking into this.  I think my main concern is that the field name has changed from `todo` at some point to `todo2`, and it's not about nicer name.  If it's the expected behavior, we'll update our docs accordingly. Thanks for the confirmation.

**Comment by Alan-Cha** [comment]
@dhmlau Ah, if this is about consistency, then I do not think this issue is resolved. Many seemingly extraneous factors can affect the resulting GraphQL interface. We are looking into this issue with #120. I would hold off on updating the docs for now and I will try to resolve this as soon as possible.

**Comment by Alan-Cha** [comment]
@dhmlau I believe things should be consistent now with #138. Could you make sure that the docs look correct? Sorry about the long delay!
