### ISSUE TITLE
Support YAML

### ISSUE THREAD

**Issue by Alan-Cha** [strongloop/oasgraph#67]
According to the [specification](https://swagger.io/specification/): "An OpenAPI document that conforms to the OpenAPI Specification is itself a JSON object, which may be represented either in JSON or YAML format."

We currently only support JSON. We should make a check for YAML. 

Related: issue #66

**Comment by ErikWittern** [comment]
@Alan-Cha I think that we should consider this in relation to separating OASGraph core from OASGraph CLI (https://github.com/strongloop/oasgraph/issues/59). I don't think that the core component requires YAML support, because in the use as a library, the application using OASGraph is responsible for producing an in-memory representation of the OAS. The CLI, however, should be able to handle YAML documents for convenience purposes.

**Comment by wtrocki** [comment]
I came over this. I fully agree with the author. YAML support is not needed, however it will be nice to have this in the readme as people may still try to use YAML examples. Creating quick PR.

**Comment by Alan-Cha** [comment]
@wtrocki Thanks for your input! I believe there may be some miscommunication. The CLI has JSON/YAML support and the library only has JSON support. 

The PR you filed #236 is a bit misleading as the CLI does indeed have YAML support.

**Comment by wtrocki** [comment]
@Alan-Cha - ok. I was using sample yaml file and got strange result so assumed that it did not supported it. I will close PR. Thank you for very quick response.

**Comment by Alan-Cha** [comment]
@wtrocki Oh, interesting! Were you able to diagnose the problem?

**Comment by wtrocki** [comment]
I got now example petstore api and it simply works so problem was 100% on my side. I started messing with extra extension fields for https://github.com/IBM/openapi-to-graphql/issues/235
