### ISSUE TITLE
Documentation Request: LB4 vs OASGraph

### ISSUE THREAD

**Issue by Vandivier** [strongloop/oasgraph#81]
This is a request for documentation, not a functional issue.

As the README mentions, there are already similar projects. Why use OASGraph? One reason might be that it's the most polished solution, or the 89.5% conversion success rate, but another reason would be that developers trust StrongLoop and are looking specifically for a solution to enhance a LoopBack implementation.

Questions:
1 - Why use OASGraph instead of LoopBack?
2 - How / Why to use OASGraph *with* LoopBack?
3 - Why the answer to #2 is better than the basic Express + LB + GraphQL solution [described on Stack Overflow](https://stackoverflow.com/questions/37376631/how-to-use-relay-graphql-with-loopback).
4 - How close is OASGraph to production-ready?

I bring this up mainly because LB4 recently went in GA release and in the announcement, the [LB team highlighted OASGraph](https://strongloop.com/strongblog/loopback-4-ga).

I imagine many developers, like me, are wondering "I'm using LB3 right now and GraphQL seems cool. Should I migrate to LB4 or go straight to OASGraph or some other GraphQL solution?"

Thanks!

**Comment by ErikWittern** [comment]
Hey, thanks for the input! In general, you point out that the messaging around OASGraph is somewhat ambiguous. To provide some context: OASGraph originated as a project within IBM Research. We open-sourced OASGraph as part of the StrongLoop organization because we felt that OASGraph naturally complements LoopBack (i.e., LoopBack produces OpenAPI Specifications, which can be fed into OASGraph). What OASGraph offers is to quickly get a GraphQL interface up, without having to write code, and addressing concerns like authentication, data sanitation, or nesting of types. We will try to improve our communication about the purpose of OASGraph and it's relation to LoopBack.

With this in mind, to briefly answer your questions:

1. OASGraph is not intended as an alternative to LoopBack - they have different purposes: LoopBack creates and operates REST(-like) APIs, OASGraph generates GraphQL wrappers for REST(-like) APIs - but can be used in conjunction with it. OASGraph _can_ also be used independently of LoopBack.
2. For now, you take the OAS produced by LoopBack and feed it into OASGraph, as described in the [LoopBack and OASGraph tutorial](https://github.com/strongloop/oasgraph/blob/master/docs/tutorials/loopback.md). In the future, a more tight integration of OASGraph into LoopBack is possible, but still to be discussed. It's not necessary to use OASGraph with LoopBack - we see it as a simple way to get into GraphQL if you already have a LoopBack API / API described by an OAS in general.
3. There are definitely other solutions for creating GraphQL servers, also in relation to LoopBack (e.g., the StackOverflow question you linked pointed us to the [GraphQL Server for Loopback](https://github.com/Tallyb/loopback-graphql), which we have no experience with, though). What way works best depends on the specific project and requirements.
4. This, again, depends on your specific requirements. Software nowadays is constantly evolving. You might find that OASGraph works very well for you. You might also find bugs, in which case we are happy to help you fix them.

Overall, we think you should give OASGraph a try, because the effort required for installing and running it is very small - especially when using [the CLI](https://github.com/strongloop/oasgraph/tree/master/packages/oasgraph-cli).

**Comment by Vandivier** [comment]
Excellent response. Happy to close.
