### ISSUE TITLE
How to generate GraphQL schema across multiple OpenApi3 specs?

### ISSUE THREAD

**Issue by JHibbard** [strongloop/oasgraph#82]
Can oasgraph generate one GraphQL schema across multiple OpenAPI3 specs?  I have several OpenAPI3 compliant services with links that reference each other.  It'd be amazing to use GraphQL to query across them.

**Comment by ErikWittern** [comment]
@JHibbard This feature is not yet supported by OASGraph, but falls neatly into its intended capabilities. One challenge will be to avoid collision between GraphQL type names. Another consideration is whether OASGraph should be passed a list of OAS, or whether a single OAS that defines links using `operationRef`s could be the starting point.

**Comment by amnuts** [comment]
I would also be really interested in seeing this functionality!  I have several microservices which each have their own OpenAPI spec and would like to put a GraphQL gateway in front of them.  Being able to supply all the oas specs and have it produce one unified GraphQL schema would be fantastic.

**Comment by ErikWittern** [comment]
@amnuts We are currently fixing some issues for a new minor version (which will come out soon), and then want to look into this one!

We will likely approach this in different stages, i.e., initially throw errors if there is collusion between the type names used in the OAS, and eventually mitigate these problems.

**Comment by amnuts** [comment]
That's great to hear @ErikWittern, thanks!  Right now we're kind of working around by converting each of the OAS files in turn with oasgraph and then using graphql-tools to merge the schemas together in the end.  But I feel that's probably going to limit us by not allowing the 'links:' from one spec to another - not sure, yet.

But thank you so much for this project!  It was amazing to be able to use an OAS file and have it converted automatically to GraphQL including all of the resolvers and mutations, which meant we only needed to concentrate on building a good foundation spec.  Brilliant!

**Comment by Alan-Cha** [comment]
@JHibbard @amnuts Yesterday I added support for multiple OASs! I am still working on documentation and other improvements but if you would like to give it try, please do! 

It would also be nice just to have some early feedback so I know what to do next because as of now, we only have a basic version with limited collision handling (if `operationIds` or `securitySchemes` are the same, OASGraph will simply pick from one OAS and provide an error message. To mitigate this, you may need to use the new [`operationIdFieldNames`](https://github.com/strongloop/oasgraph/tree/master/packages/oasgraph#options) option).

***

Now, instead of providing a Swagger or an OAS, you can _also_ provide an array of a mix of Swaggers and OASs like in the following: 

```
OasGraph.createGraphQlSchema([oas1, oas2, oas3])
```

***

I have currently configured the example GraphQL server ([packages/oasgraph/test/example_gql_server.js](https://github.com/strongloop/oasgraph/blob/master/packages/oasgraph/test/example_gql_server.js)) to use this feature. Because the file will likely change over time, I also created a [gist](https://gist.github.com/Alan-Cha/4c6754b920bc8cbb3e3498dbd87f7dcb) with the same code. 

To run it, you just need to run:
```
cd packages/oasgraph/test/
node example_gql_server.js
```
And go to [http://localhost:3000/graphql](http://localhost:3000/graphql)

And do make queries against it, you will also need to run the example API servers:
```
# in a second tab
cd packages/oasgraph/test/
node example_api_server.js
```

```
# in a third tab
cd packages/oasgraph/test/
node example_api3_server.js
```

You can see some example queries [here](https://github.com/strongloop/oasgraph/blob/master/packages/oasgraph/test/example_api3.test.js).

***

Upcoming work:
* Documentation
* CLI support
* **Links across OASs**

**Comment by amnuts** [comment]
This is really awesome @Alan-Cha, thanks!  I'll be able to give this a go next week, so will see how it goes then.  I'm looking forward to trying it out!

**Comment by ErikWittern** [comment]
This is addressed by the above commits and PRs.
