### ISSUE TITLE
Library tutorial example code throws an error

### ISSUE THREAD

**Issue by simax** [strongloop/oasgraph#90]
**I Received the following error whilst trying to run the example code**
`Enum type default cannot include value true/false`

**To Reproduce**

1. Installed node version 10.15.0 on windows 10 machine
2. Used the following package.json:
```
{
  "name": "myapp",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "start": "node app.js"
  },
  "dependencies": {
    "body-parser": "^1.18.3",
    "express": "~4.16.0",
    "express-graphql": "^0.7.1",
    "graphql": "^14.0.2",
    "oasgraph": "^0.12.0"
  }
}
```
3. Copied the contents of 'https://watson-api-explorer.ng.bluemix.net/listings/language-translator-v2.json' into a locall `swagger.json` file.

4. Used the following code in `app.js`
```
const express = require('express')
const graphqlHTTP = require('express-graphql')
const OASGraph = require('oasgraph')
const bodyParser = require('body-parser')

async function startServer () {
  // use OASGraph to create a GraphQL schema:
  const oas = require('./swagger.json')
  const {schema} = await OASGraph.createGraphQlSchema(oas)

  // setup Express.js app and serve the schema:
  const app = express()
  app.use(bodyParser.json())

  app.use('/', graphqlHTTP({
    schema: schema,
    graphiql: true
  }))

  app.listen(3000, () => {
    console.log("GraphQL => http://localhost:3000/graphiql")
  })
}

// kick things off:
startServer()
```
5. Ran node app.js from the command line
6. Navigated to `http://localhost:3000/graphiql` in the browser

**Expected behavior**
To be able to make `graphql` queries
 
But received the following error:
```
{
  "errors": [
    {
      "message": "Enum type default cannot include value: true."
    },
    {
      "message": "Enum type default cannot include value: false."
    }
  ]
}
```

If I change the following definition in the swagger json the problem goes away: 
```
"name": "default",
  "in": "query",
  "description": "If the default parameter isn't specified, the service will return all models (default and non-default) for each language pair. To return only default models, set this to `true`. To return only non-default models, set this to `false`.",
  "required": false,
  "type": "boolean",
  "enum": [
  "xtrue",
  "yfalse"
  ],  
```
(Notice I changed `true` to `xtrue` and `false` to `xfalse`)

But I assume that's not the correct thing to do.

**Comment by Alan-Cha** [comment]
I believe the problem is that GraphQL does not allow enums to contain the strings `true` and `false`. 

We mentioned this in our [paper](https://arxiv.org/abs/1809.08319). If you're curious, here is the excerpt.

```
Sanitation Error: Sanitation of type, argument, or field names fails (see
Section 3.1). The errors thrown by OASGraph result from attempts to sanitize enum values of type boolean. While such enumeration values are valid
in schemas objects, they are not valid in GraphQL enum types, specifically,
the strings true and false are forbidden as enum values [3]. Because Swagger2GraphQL does not perform sanitation, it does not produce such errors.
```

Unfortunately, there isn't much we can do. This is just a mismatch between REST-like and GraphQL.

***

I wasn't sure if you could get the tutorial to work (could you?) but if you still need help, perhaps you can try the [`qs` option](https://github.com/strongloop/oasgraph/tree/master/packages/oasgraph#options), which would allow you to send the parameter manually. 

***

It's unfortunate that the tutorial doesn't work seamlessly anymore. Honestly, we do need to update it. `v2` is deprecated as IBM now supports `v3`. 

Here is the [`v3` OAS](https://watson-api-explorer.ng.bluemix.net/listings/language-translator-v3.json) if you want to experiment...

***

We have new tutorials in the works and we're working on creating a dedicated examples folder in our monorepo so just keep an eye out!

**Comment by simax** [comment]
Thanks Alan. Personally I'm not too worried about the tutorial now I've managed to get OASGraph working with my own API. Good to know you've got other tutorials in the works though.
