### ISSUE TITLE
Missing query schemas and better schema names

### ISSUE THREAD

**Issue by simax** [strongloop/oasgraph#92]
I'm using a library that produces a swagger 2.0 doc (see attached) and I'm wanting to use that generated doc as the basis of my GraphQL schema. I have certain amount of control over the swagger doc that gets created - I can, for instance, generate my own operationId's.

I'm using OASGraph as a library.

My problem is 2 fold. 

1. Once I've generated the swagger document, OASGraph appears to ignore many of the query schemas. i.e When I look at the  documentation produced at localhost:3000/graphql many of the query schemas are missing. i.e. The query schemas for orders and customers and address are all missing. Am I doing something wrong?

2. The naming of schemas is inconsistent. How could I remedy this? OperationId would have been useful but I see you seem to have already [ruled this option out](https://github.com/strongloop/oasgraph/issues/9). Can you advise how I might achieve better schema names.  

[swagger.txt](https://github.com/strongloop/oasgraph/files/2779166/swagger.txt)

**Comment by Alan-Cha** [comment]
I believe I know some of the problems you experiencing! 

1. Recall that OASGraph is built around OAS 3 and not Swagger 2. We use the [swagger2openapi](https://www.npmjs.com/package/swagger2openapi) to convert Swagger files into OAS ones. In your Swagger, the request body is sent in `GET` operations but you cannot do this in OAS. `POST` operations, however, can have [request bodies](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#requestBodyObject) in OAS. 

I do not think just changing `GET` to `POST` in the Swagger will solve the problem. I tried it using the [online version of the library](https://mermade.org.uk/openapi-converter) and although the HTTP method changed, the library does not create a request body object. You will need to define it yourself. 

2. You can create better schema names by storing the schema of the operation in the [components object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#componentsObject) as a [schema object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#schemaObject) and then referencing the schema object in the operation.

Something like this if you are not familiar with the syntax:

```
"application/json": {
        "schema": {
                "$ref": "#/components/schemas/Pet"
        }
}
``` 

If you're wondering why we opt for something so out-of-the-way, it's because we believe this is the method that can produce the most suitable name. The assumption is that if the user defines a schema in the components object, it may be reused and thus, will have a generalized name. 

We have a priority order, which can be found [here](https://github.com/strongloop/oasgraph/blob/master/packages/oasgraph/src/preprocessor.ts#L426).

But what you brought up about `operationIDs` is interesting... Indeed, changing the `operationID` would be easiest for the user. We designed OASGraph with people who have preexisting OASs in mind. We created these previously mentioned methods that would be able

**Comment by Alan-Cha** [comment]
Sorry, I accidentally closed the issue 😅

**Comment by simax** [comment]
Hi Alan,

Thanks for your considered and detailed response (as per usual from you guys). It's much appreciated.

The library I'm using to produce the swagger file now has a version in beta that should generate an OAS version 3 document. I'm currently investigating that and hopefully that will produce a file that works better with OASGraph. With that in mind I will close this issue for now.
